const DialogIdConstants = Object.freeze({
    CAPTURE_EVIDENCE_DIALOG: 'CAPTURE_EVIDENCE_DIALOG',
    EMERGENCY_DIALOG: 'EMERGENCY_DIALOG',
    RETRIEVE_EVIDENCE_DIALOG: 'RETRIEVE_EVIDENCE_DIALOG',
    AUTHENTICATION_DIALOG: 'AUTHENTICATION_DIALOG',
    CAPTURE_DIALOG: 'CAPTURE_DIALOG',
    OTHER_HELP_DIALOG: 'OTHER_HELP_DIALOG',
    CALL_POLICE_DIALOG: 'CALL_POLICE_DIALOG',
    CALL_POLICE_ON_BEHALF_OF_DIALOG: 'CALL_POLICE_On_BEHALF_OF_DIALOG',
    TEXT_PROMPT: 'TEXT_PROMPT',
    CONFIRM_PROMPT: 'CONFIRM_PROMPT',
    ATTACHMENT_PROMPT: 'ATTACHMENT_PROMPT',
    MAIN_MENU_DIALOG: 'MAIN_MENU_DIALOG'
});

module.exports.CAPTURE_EVIDENCE_DIALOG = DialogIdConstants.CAPTURE_EVIDENCE_DIALOG;
module.exports.EMERGENCY_DIALOG = DialogIdConstants.EMERGENCY_DIALOG;
module.exports.RETRIEVE_EVIDENCE_DIALOG = DialogIdConstants.RETRIEVE_EVIDENCE_DIALOG;
module.exports.AUTHENTICATION_DIALOG = DialogIdConstants.AUTHENTICATION_DIALOG;
module.exports.CAPTURE_DIALOG = DialogIdConstants.CAPTURE_DIALOG;
module.exports.OTHER_HELP_DIALOG = DialogIdConstants.OTHER_HELP_DIALOG;
module.exports.CALL_POLICE_DIALOG = DialogIdConstants.CALL_POLICE_DIALOG;
module.exports.CALL_POLICE_ON_BEHALF_OF_DIALOG = DialogIdConstants.CALL_POLICE_ON_BEHALF_OF_DIALOG;
module.exports.TEXT_PROMPT = DialogIdConstants.TEXT_PROMPT;
module.exports.CONFIRM_PROMPT = DialogIdConstants.CONFIRM_PROMPT;
module.exports.ATTACHMENT_PROMPT = DialogIdConstants.ATTACHMENT_PROMPT;
module.exports.MAIN_MENU_DIALOG = DialogIdConstants.MAIN_MENU_DIALOG;
